# image will be published to ghcr.io/<user>/<name>
name: silverblue-customized
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 42 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system/usr
        destination: /usr
      - source: system/etc
        destination: /etc
          # copies config/files/usr into your image's /usr.
          # put configuration files you want in /etc/ on a booted system 
          # in /usr/etc/ in the image. read more in files module reference.

  - type: bling
    install:
      - rpmfusion

  - type: rpm-ostree
    repos: # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/atim/lazygit/repo/fedora-%OS_VERSION%/atim-lazygit-fedora-%OS_VERSION%.repo # LazyGit
      - https://copr.fedorainfracloud.org/coprs/sneexy/python-validity/repo/fedora-%OS_VERSION%/sneexy-python-validity-fedora-%OS_VERSION%.repo # python-validity - Driver for Validity Fingerprint Reader
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo # Source of tailscale
    install:
      - xonsh # Shell
      - python3-prompt-toolkit # Xonsh Dependency
      - python3-pygments # Xonsh Dependency
      - python3-setproctitle # Xonsh Dependency
      - gnome-console # Terminal Emulator
      - gnome-tweaks # GNOME Customization Application
      #- libavcodec-freeworld # Non-free Codecs
      - most # Pager
      - neovim # Text Editor
      - lazygit # Dependency of LazyVim
      - nextcloud-client-nautilus # Nextcloud integration for File Manager
      - nautilus-gsconnect # KDE Connect integration for File Manager
      - openssl # KDE Connect Dependency
      - piper # Mouse Manager
      - setroubleshoot # SELinux Client
      - tmux # Terminal Multiplexer
      - virt-manager # Libvirt Client
      - libvirt # Virtualization 
      - wireguard-tools # VPN
      - langpacks-en # English Language Pack
      - wl-clipboard # CLI copy/paste - Needed to copy to system clipboard
      #- libgda # Pano Dependency
      #- libgda-sqlite # Pano Dependency
      - gcc-c++ # Dependency of 'nvim-treesitter'
      - tailscale # Peer to peer VPN
      - fzf # Fuzzy Finder
        # BEGIN python-validity - Driver for Validity Fingerprint Reader
      - open-fprintd
      - fprintd-clients
      - fprintd-clients-pam
      - python3-validity
        # END python-validity - Driver for Validity Fingerprint Reader
      - meld # Git Merger
    remove:
      - gnome-system-monitor
      - firefox # Installed as Flatpak
      - firefox-langpacks # Dependency of Flatpak, that must be explicitly removed
        # BEGIN python-validity - Driver for Validity Fingerprint Reader
      - fprintd
      - fprintd-pam
        # END python-validity - Driver for Validity Fingerprint Reader

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      # repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      # repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        - ch.protonmail.protonmail-bridge
        - com.github.tchx84.Flatseal # Flatpak Permission Manager
        - io.github.flattool.Warehouse # Flatpak Manager
        - com.jgraph.drawio.desktop # Diagram Application
        - com.mattjakeman.ExtensionManager # Gnome Extension Manager
        - com.nextcloud.desktopclient.nextcloud # File Sync
        - com.spotify.Client # Music Streaming
        - com.valvesoftware.Steam # Game Launcher/Store
        - com.yubico.yubioath # TOTP Client for Yubikey
        - org.gnome.Fractal # Matrix Chat Client
        - org.freecadweb.FreeCAD # 3D CAD
        - org.keepassxc.KeePassXC # Password Manager
        - org.libreoffice.LibreOffice # Office Suite
        - org.openscad.OpenSCAD # Programmatic 3D CAD
        - org.rncbc.qpwgraph # Audio Patch Bay
        - org.videolan.VLC # Video Player
        - com.github.wwmm.easyeffects # Audio Effect Rack
        - com.belmoussaoui.Decoder # QR-code Application
        - com.github.Eloston.UngoogledChromium # Web Browser
        - com.usebottles.bottles # Wine Prefix Manager
        - org.gnome.seahorse.Application # GPG Key Manager
        - org.gnome.Evolution # EMail/Calender/To Do
        - com.github.iwalton3.jellyfin-media-player # Desktop app for Jellyfin
        - com.ultimaker.cura # 3D Printer Slicer
        - dev.geopjr.Tuba # Mastodon Client
        - org.cryptomator.Cryptomator # Encrypted File Vault
        - org.gimp.GIMP # Image Manipulation
        - org.zotero.Zotero # Citation Management and Research Organization
        - com.github.johnfactotum.Foliate # EPUB reader
        - org.gnome.baobab # Disk Usage Analyzer
        - org.gnome.Characters # Symbols and Characters Browser
        - org.gnome.Loupe # Image Viewer
        - org.gnome.Cheese # Web Cam Application
        - org.gnome.NautilusPreviewer # Nautilus File Previews
        - io.freetubeapp.FreeTube # Youtube Client
        - org.gnome.TextEditor # Text Editor
        - org.gnome.Calculator # Gnome Calculator
        - io.missioncenter.MissionCenter # Process & System Monitor
        - org.mozilla.firefox # Web Browser
        - com.mardojai.ForgeSparks # Code forge notifications
        - org.gnome.Evince # Document/PDF Viewer
        - com.calibre_ebook.calibre # E-book organization
        - it.mijorus.gearlever # AppImage Manager
        - org.inkscape.Inkscape # Image Editor
        - org.kde.kdenlive # Video Editor
        - org.qbittorrent.qBittorrent # Torrent Client
        - org.wireshark.Wireshark # Network Sniffer
        - org.torproject.torbrowser-launcher # Tor Browser
        - org.gnome.Todo # Gnome ToDo App
        # - org.gnome.Loupe
        # - one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).
        # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),
        # only normal flatpak applications are (like Floorp Lightning web browser in this example).
        # Installing different branches of the same Flatpak is not supported.
      remove:
        - org.fedoraproject.MediaWriter
        - org.gnome.Geary
  - type: fonts
    fonts:
      nerd-fonts:
        - ShareTechMono
      google-fonts:
        - NunitoSans

  - type: gnome-extensions
    install:
      #- smart-auto-movekhimaros.com.v28 # Moves applications to specified Workspace
      - caffeinepatapon.info.v56 # Keep screen on during inactivity
      - gsconnectandyholmes.github.io.v62 # KDEConnect for Gnome SHell
      #- appindicatorsupportrgcjonas.gmail.com.v59 # AppIndicator (tray icons)
      - windowsNavigatorgnome-shell-extensions.gcampax.github.com.v71 # Navigate windows in Overview using Alt
      # Incompatible with GNOME 46 # - panoelhan.io.v22 # Clipboard Manager
      - CoverflowAltTabpalatis.blogspot.com.v78 # Pretty Alt+Tab
      - pinned-apps-in-appgridbrunosilva.io.v2 # Keeps Favorite apps in App Grid
      - tailscalejoaophi.github.com.v19 # Adds Tailscaleto Quick Settings

  - type: gschema-overrides
    include:
      - zz1-settings.gschema.override # test & compile the override file included in config/gschema-overrides/zz1-settings.gschema.override

  - type: chezmoi
    # () Git repository to initialize
    repository: "git@gitlab.com:unshippedreminder/dotfiles.git" # Required - Default: n/a  - Expects type: string
    # Enable the modules services globally for all users
    # enable-all-users: true # Optional - Default: true - Expects type: boolean
    # Dotfiles will be updated with this interval
    # run-every: '1d' # Optional - Default: '1d' - Expects type: string
    # Dotfile updates will wait this long after a boot before running
    # wait-after-boot: '5m' # Optional - Default: '5m' - Expects type: string
    # Disable the service that initializes `repository` on users that are logged in or has linger enabled
    # disable-init: false # Optional - Default: false - Expects type: boolean
    # Disable the timer that updates chezmoi with the interval set above
    # disable-update: false # Optional - Default: false - Expects type: boolean
    # Policy for handling file that has changed on disk compared to your repo. Accepts "skip" or "replace"
    file-conflict-policy: "replace" # Optional - Default: "skip" - Expects type: string

  - type: brew
    # List of applications to install are in ../files/usr/share/bluebuild/brew-applications/applications.env

  - type: systemd
    user:
      enabled:
        - brew-applications.service

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
