# image will be published to ghcr.io/<user>/<name>
name: silverblue-customized
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 39 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr
          # copies config/files/usr into your image's /usr.
          # put configuration files you want in /etc/ on a booted system 
          # in /usr/etc/ in the image. read more in files module reference.

  - type: rpm-ostree
    repos: # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      - gnome-console # Terminal Emulator
      - gnome-tweaks # GNOME Customization Application
      - libavcodec-freeworld # Non-free Codecs
      - most # Pager
      - neovim # Text Editor
      - nextcloud-client-nautilus # Nextcloud integration for File Manager
      - nautilus-gsconnect # KDE Connect integration for File Manager
      - openssl # KDE Connect Dependency
      - piper # Mouse Manager
      - python3-prompt-toolkit # Xonsh Dependency
      - python3-pygments # Xonsh Dependency
      - python3-setproctitle # Xonsh Dependency
      - setroubleshoot # SELinux Client
      - tmux # Termnal Multiplexer
      - virt-manager # Libvirt Client
      - libvirt # Virtualization 
      - wireguard-tools # VPN
      - langpacks-en # English Language Pack
      # Gnome Extensions
      - gnome-shell-extension-auto-move-windows
      - gnome-shell-extension-caffeine
      - gnome-shell-extension-gsconnect
      - gnome-shell-extension-appindicator
      - gnome-shell-extension-windowsNavigator
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      # - firefox
      # - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      # repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      # repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        - ch.protonmail.protonmail-bridge
        - com.github.tchx84.Flatseal # Flatpak Permission Manager
        - io.github.flattool.Warehouse # Flatpak Manager
        - com.jgraph.drawio.desktop # Diagram Application
        - com.mattjakeman.ExtensionManager # Gnome Extension Manager
        - com.nextcloud.desktopclient.nextcloud # File Sync
        - com.spotify.Client
        - com.valvesoftware.Steam
        - com.yubico.yubioath # TOTP Client for Yubikey
        - org.gnome.Fractal # Matrix Chat Client
        - org.freecadweb.FreeCAD # 3D CAD
        - org.keepassxc.KeePassXC # Password Manager
        - org.libreoffice.LibreOffice
        - org.openscad.OpenSCAD # Programmatic 3D CAD
        - org.rncbc.qpwgraph # Audio Patch Bay
        - org.videolan.VLC # Video Player
        - com.github.wwmm.easyeffects # Audio Effect Rack
        - com.belmoussaoui.Decoder # QR-code Application
        - com.github.Eloston.UngoogledChromium
        - com.usebottles.bottles # Wine Prefix Manager
        - org.gnome.seahorse.Application # GPG Key Manager
        - org.gnome.Evolution # EMail/Calender/To Do
        - com.github.iwalton3.jellyfin-media-player
        - com.ultimaker.cura # 3D Printer Slicer
        - dev.geopjr.Tuba # Mastodon Client
        - org.cryptomator.Cryptomator # Encrypted File Vault
        - org.gimp.GIMP # Image Manipulation
        - org.zotero.Zotero # Citation Management and Research Organization
        - com.github.johnfactotum.Foliate # EPUB reader
        - de.haeckerfelix.Fragments # Torrent Client
        - org.gnome.baobab # Disk Usage Analyzer
        - org.gnome.Characters # Symbols and Characters Browser
        - org.gnome.Loupe # Image Viewer
        - org.gnome.Cheese # Web Cam Application
        - org.gnome.NautilusPreviewer # Nautilus File Previews
        - com.protonvpn.www # ProtonVPN
        - io.freetubeapp.FreeTube # Youtube Client
        # - org.mozilla.firefox
        # - org.gnome.Loupe
        # - one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).
        # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),

      # only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Installing different branches of the same Flatpak is not supported.
      remove:
        - org.fedoraproject.MediaWriter
        - org.gnome.Geary
        # - org.gnome.eog
  - type: fonts
    fonts:
      nerd-fonts:
        - ShareTechMono

  - type: gschema-overrides
    include:
      - zz1-settings.gschema.override # test & compile the override file included in config/gschema-overrides/zz1-myoverride.gschema.override

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
