# image will be published to ghcr.io/<user>/<name>
name: silverblue-customized
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 39 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr
          # copies config/files/usr into your image's /usr.
          # put configuration files you want in /etc/ on a booted system 
          # in /usr/etc/ in the image. read more in files module reference.

  - type: rpm-ostree
    repos: # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      - gnome-console
      - gnome-tweaks
      - libavcodec-freeworld
      - most
      - neovom
      - nextcloud-client-nautilus
      - openssl
      - piper
      - python3-prompt-toolkit
      - python3-pygments
      - python3-setproctitle
      - setroubleshoot
      - tmux
      - virt-manager
      - wireguard-tools
    remove:
      - gnome-terminal
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      # - firefox
      # - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      # repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      # repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        - ch.protonmail.protonmail-bridge
        - com.github.tchx84.Flatseal
        - com.jgraph.drawio.desktop
        - com.mattjakeman.ExtensionManager
        - com.nextcloud.desktopclient.nextcloud
        - com.spotify.Client
        - com.valvesoftware.Steam
        - com.yubico.yubioath
        - im.riot.Riot
        - org.freecadweb.FreeCAD
        - org.keepassxc.KeePassXC
        - org.libreoffice.LibreOffice
        - org.openscad.OpenSCAD
        - org.rncbc.qpwgraph
        - org.videolan.VLC
        - com.github.wwmm.easyeffects
        - com.belmoussaoui.Decoder # QR-code Application
        - com.github.Eloston.UngoogledChromium
        - com.usebottles.bottles
        - org.gnome.seahorse.Application
        - org.gnome.Evolution
        - com.github.iwalton3.jellyfin-media-player
        - com.ultimaker.cura
        - dev.geopjr.Tuba # Mastodon Client
        - org.cockpit_project.CockpitClient
        - org.cryptomator.Cryptomator # Encrypted File Vault
        - org.gimp.GIMP
        - org.zotero.Zotero
        - com.github.johnfactotum.Foliate # EPUB reader
        - com.github.Eloston.UngoogledChromium
        # - org.mozilla.firefox
        # - org.gnome.Loupe
        # - one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).
        # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),

      # only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Installing different branches of the same Flatpak is not supported.
      remove:
        - org.gnome.Calculator
        - org.fedoraproject.MediaWriter
        - org.gnome.Geary
        # - org.gnome.eog
  - type: fonts
    fonts:
      nerd-fonts:
        - SourceCodePro

#  - type: gschema-overrides
#    include:
#      - zz1-myoverride.gschema.override # test & compile the override file included in config/gschema-overrides/zz1-myoverride.gschema.override

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
